routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('prueba',function(){
	return view('prueba');
});

Route::get('/', function () {
    return view('welcome');
});
Route::get('menu', function () {
    return view('Plantillas.principal');
});


Route::get('listar', function () {
    return view('clientes.editarCliente');
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix'=>'admin'], function(){
Route::resource('usuario','userController');
Route::resource('cliente','ClienteController');
Route::resource('estadoFactura','Estado_facturaController');
Route::resource('factura','FacturaController');
Route::resource('formaPago','Forma_pagoController');
Route::resource('perfil','PerfilController');
Route::resource('productoFactura','Prod_facturaController');
Route::resource('producto','ProductoController');


});
route::get('eliminar/destroy/{id}','PerfilController@destroy')->name('admin.eliminar');
route::get('eliminarCliente/destroy/{id}','ClienteController@destroy')->name('admin.eliminarCliente');

app/Cliente.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Cliente extends Model
{
    protected $table="clientes";
    protected $fillable=['Nombre','Nit','Correo','Direccion','Ciudad','Telefono'];
}

app/Http/Controllers/ClienteController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use\App\Cliente;

class ClienteController extends Controller
{
    
    public function index()
    {
        
        $cliente = Cliente::orderBy('Nombre', 'ASC')->paginate(5);
        return view('clientes.listarCliente')->with('cliente',$cliente);
        
    }

    
    public function create()
    {
        return view('clientes.crearCliente');
    }

    public function store(Request $request)
    {

        $crearUsuario=new Cliente($request->all());
        $crearUsuario->Nit=$request->nit;
        $crearUsuario->Nombre=$request->nombre;
        $crearUsuario->Correo=$request->correo;
        $crearUsuario->Telefono=$request->telefono;
        $crearUsuario->Direccion=$request->direccion;
        $crearUsuario->Ciudad='Pereira';

         $crearUsuario->save();
        flash('El Usuario '.$request->nombre. ' fue creado sastifactoriamente');
        return redirect()->route('cliente.create');

        //otra forma de crear usuarios

        // $cliente=Cliente::create([

        //     'Nit'=> $request->get('nit'),
        //     'Nombre'=> $request->get('nombre'),
        //     'Correo'=> $request->get('correo'),
        //     'Telefono'=> $request->get('telefono'),
        //     'Direccion'=> $request->get('direccion'),
        //     'Ciudad'=> $request->get('ciudad'),

        // ]);

        // $cliente->save();
        // flash('El Usuario '.$request->nombre. ' fue creado sastifactoriamente');
        // return redirect()->route('cliente.create');

    }

    
    public function show($id)
    {
      
    }

    public function edit($id)
    {
     $dato=Cliente::find($id);
     return view('clientes.editarCliente', compact('dato'));
    }

  
    public function update(Request $request, $id)
    {
        $actualizarCliente=Cliente::find($id);
        $actualizarCliente->Nit=$request->nit;
        $actualizarCliente->Nombre=$request->nombre;
        $actualizarCliente->Correo=$request->correo;
        $actualizarCliente->Telefono=$request->telefono;
        $actualizarCliente->Ciudad=$request->ciudad;
       $actualizarCliente->save();
       return redirect()->route('cliente.index');
    }

    
    public function destroy($id)
    {
        $eliminarCliente=Cliente::find($id);
        // return ($eliminarCliente);
        
        $eliminarCliente->delete();
        return redirect()->route('cliente.index');


    }
}

resources/views/clientes/crearCliente.blade.php
@extends('Plantillas.principal')
@extends('Plantillas.librerias')

@section('cuerpo')


<div class="container">

  {{--   <form class="well form-horizontal" action=" " method="post"  id="contact_form"> --}}
      {!! Form::open(['route'=>'cliente.store', 'method'=>'post','class'=>'well form-horizontal']) !!}
<fieldset>

<!-- Form Name -->
<legend>Crear cliente<br>
  
  @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

  @include('flash::message')

</legend>


<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label">Cedula o Nit</label>  
  <div class="col-md-6 inputGroupContainer">
  <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
  <input  name="nit" id="nit" placeholder="numero de cedula o nit" class="form-control"  type="text">
    </div>
  </div>
</div>

<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label" >Nombre o Empresa</label> 
    <div class="col-md-6 inputGroupContainer">
    <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
  <input name="nombre" id="nombre" placeholder="Escriba su nombe o empresa" class="form-control"  type="text">
    </div>
  </div>
</div>

<!-- Text input-->
       <div class="form-group">
  <label class="col-md-4 control-label">Correo</label>  
    <div class="col-md-6 inputGroupContainer">
    <div class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
  <input name="correo" id="correo" placeholder="E-Mail Address" class="form-control"  type="text">
    </div>
  </div>
</div>


<!-- Text input-->
       
<div class="form-group">
  <label class="col-md-4 control-label">Tel&eacutefono</label>  
    <div class="col-md-6 inputGroupContainer">
    <div class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-earphone"></i></span>
  <input name="telefono" id="telefono" placeholder="3112222552" class="form-control" type="text">
    </div>
  </div>
</div>

<!-- Text input-->
      
<div class="form-group">
  <label class="col-md-4 control-label">Direcci&oacuten</label>  
    <div class="col-md-6 inputGroupContainer">
    <div class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-home"></i></span>
  <input name="direccion" id="direccion" placeholder="Address" class="form-control" type="text">
    </div>
  </div>
</div>

<!-- Text input-->
 
<div class="form-group">
  <label class="col-md-4 control-label">Ciudad</label>  
    <div class="col-md-6 inputGroupContainer">
    <div class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-home"></i></span>
  <input name="ciudad" id="ciudad" placeholder="city" class="form-control"  type="text">
    </div>
  </div>
</div>

<!-- Button -->
<div class="form-group">
  <label class="col-md-4 control-label"></label>
  <div class="col-md-6">
    <button type="submit" class="btn btn-primary" >Guardar <span class="glyphicon glyphicon-send"></span></button>
  </div>
</div>

</fieldset>
{!! Form::close() !!} 
</div>

    </div><!-- /.container -->


  @endsection

resources/views/clientes/editarCliente.blade.php
@extends('Plantillas.principal')
@extends('Plantillas.librerias')

@section('cuerpo')


<div class="container">

  {{--   <form class="well form-horizontal" action=" " method="post"  id="contact_form"> --}}
      {!! Form::open(['route'=>['cliente.update',$dato], 'method'=>'put','class'=>'well form-horizontal']) !!}
<fieldset>

<!-- Form Name -->
<legend class="btn-primary"><center><h3>Actualizar cliente</h3></center><br>
  
  @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

  @include('flash::message')

</legend>

<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label">Cedula o Nit</label>  
  <div class="col-md-6 inputGroupContainer">
  <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
  <input  name="nit" id="nit" value="{{ $dato->Nit }}" placeholder="numero de cedula o nit" class="form-control"  type="text">
    </div>
  </div>
</div>

<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label" >Nombre o Empresa</label> 
    <div class="col-md-6 inputGroupContainer">
    <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
  <input name="nombre" id="nombre" value="{{ $dato->Nombre }}" placeholder="Escriba su nombe o empresa" class="form-control"  type="text">
    </div>
  </div>
</div>

<!-- Text input-->
       <div class="form-group">
  <label class="col-md-4 control-label">Correo</label>  
    <div class="col-md-6 inputGroupContainer">
    <div class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
  <input name="correo" id="correo" value="{{ $dato->Correo }}" placeholder="E-Mail Address" class="form-control"  type="text">
    </div>
  </div>
</div>


<!-- Text input-->
       
<div class="form-group">
  <label class="col-md-4 control-label">Tel&eacutefono</label>  
    <div class="col-md-6 inputGroupContainer">
    <div class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-earphone"></i></span>
  <input name="telefono" id="telefono" value="{{ $dato->Telefono }}" placeholder="3112222552" class="form-control" type="text">
    </div>
  </div>
</div>

<!-- Text input-->
      
<div class="form-group">
  <label class="col-md-4 control-label">Direcci&oacuten</label>  
    <div class="col-md-6 inputGroupContainer">
    <div class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-home"></i></span>
  <input name="direccion" id="direccion" value="{{ $dato->Direccion}}" placeholder="Address" class="form-control" type="text">
    </div>
  </div>
</div>

<!-- Text input-->
 
<div class="form-group">
  <label class="col-md-4 control-label">Ciudad</label>  
    <div class="col-md-6 inputGroupContainer">
    <div class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-home"></i></span>
  <input name="ciudad" id="ciudad" value="{{ $dato->Ciudad }}" placeholder="city" class="form-control"  type="text">
    </div>
  </div>
</div>

<!-- Button -->
<div class="form-group">
  <label class="col-md-4 control-label"></label>
  <div class="col-md-6">
    <button type="submit" class="btn btn-primary" >Actualizar <span class="glyphicon glyphicon-send"></span></button>
  </div>
</div>

</fieldset>
{!! Form::close() !!} 
</div>

    </div><!-- /.container -->


  @endsection

resources/views/clientes/listarCliente.blade.php
@extends('Plantillas.principal')
@extends('Plantillas.librerias')

@section('cuerpo')
<center><h2>Lista de clientes registrado</h2></center>
<br>
<a href="{{ route('cliente.create') }}" onclick="return confirm('Desea crear un nuevo cliente?')" class="btn btn-info">Agregar Cliente</a><p>
	<table class="table table-striped table-responsive">
		<tr>
			<th>Nit/cedula</th>
			<th>Nombre</th>
			<th>Correo</th>
			<th>Direci&oacuten</th>
			<th>Tel&eacutefono</th>
			<th>Ciudad</th>
			<th style="text-align:right">Editar</th>
			<th style="text-align:right">Borrar</th>
			
		</tr>

		@foreach($cliente as $dato)

		<tr>
			
			<td>{{ $dato->Nit }}</td>
			<td>{{ $dato->Nombre }}</td>
			<td>{{ $dato->Correo }}</td>
			<td>{{ $dato->Direccion}}</td>
			<td>{{ $dato->Telefono }}</td>
			<td>{{ $dato->Ciudad }}</td>
			<th style="text-align:center"><span><a href="{{ route('cliente.edit',$dato->id) }}"  class="glyphicon glyphicon-pencil"></span></a></th>
			<th style="text-align:center"><span><a href="{{ route('admin.eliminarCliente', $dato->id) }}" onclick="return confirm('Está seguro que desea eliminar el usuario?')" class="glyphicon glyphicon-trash"></span></a></th>
		</tr>
		@endforeach
	</table>
	<center>{{ $cliente->render() }}</center>

	@endsection