routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('prueba',function(){
	return view('prueba');
});

Route::get('/', function () {
    return view('welcome');
});
Route::get('menu', function () {
    return view('Plantillas.principal');
});


Route::get('listar', function () {
    return view('clientes.editarCliente');
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix'=>'admin'], function(){
Route::resource('usuario','userController');
Route::resource('cliente','ClienteController');
Route::resource('estadoFactura','Estado_facturaController');
Route::resource('factura','FacturaController');
Route::resource('formaPago','Forma_pagoController');
Route::resource('perfil','PerfilController');
Route::resource('productoFactura','Prod_facturaController');
Route::resource('producto','ProductoController');


});
route::get('eliminar/destroy/{id}','PerfilController@destroy')->name('admin.eliminar');
route::get('eliminarCliente/destroy/{id}','ClienteController@destroy')->name('admin.eliminarCliente');

resources/views/perfiles/editarPerfil.blade.php
@extends('Plantillas.principal')
@extends('Plantillas.librerias')
@section('cuerpo')

<h1><center>Editar perfil de usuario</center></h1>

@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

@include('flash::message')
<div class="panel-body">
{!! Form::model($perfil, ['route'=>['perfil.update', $perfil->id], 'method'=>'PUT']) !!}


<label for="Perfil">Perfil de usuario</label>
	
	{!! form::text('Perfil',null, ['class'=>'form-control form-group', 'required']) !!}
	{!! form::submit('Actualizar',['class'=>'btn btn-block btn-primary']) !!}
	{{-- <input type="submit" value="Actualizar" class="btn btn-block btn-primary"> --}}


{!!form::close()!!}

</div>
@endsection

resources/views/perfiles/listarPerfil.blade.php
@extends('Plantillas.principal')
@extends('Plantillas.librerias')

@section('cuerpo')
<center><h2>Lista de perfiles</h2></center><br>
<a href="{{ route('perfil.create') }}" onclick="return confirm('Desea crear un nuevo perfil?')" class="btn btn-info">Crear perfil</a><p>
	<table class="table table-striped table-responsive">
		<tr>
			<th>Codigo</th>
			<th>Perfil</th>
			<th style="text-align:right">Editar</th>
			<th style="text-align:right">Borrar</th>
			
		</tr>

		@foreach($perfil as $dato)

		<tr>
			
			<td>{{ $dato->id }}</td>
			<td>{{ $dato->Perfil}}</td>
			
			<th style="text-align:right"><span><a href="{{route('perfil.edit',$dato->id)}}" onclick="return confirm('Está seguro que desea editar el perfil?')" class="glyphicon glyphicon-pencil"></span></a></th>
			
			<th style="text-align:right"><span><a href="{{route('admin.eliminar',$dato->id)}}" onclick="return confirm('Está seguro que desea eliminar el perfil?')" class="glyphicon glyphicon-trash"></span></a></th>
		</tr>
		@endforeach
	</table>
	<center>{{ $perfil->render() }}</center>

	@endsection

resources/views/perfiles/perfil.blade.php
@extends('Plantillas.principal')
@extends('Plantillas.librerias')
@section('cuerpo')

<h1>Crear perfil de usuario</h1>
@include('flash::message')
<div class="panel-body">
{!! Form::open(['route'=>'perfil.store', 'method'=>'post']) !!}

<label for="perfil">Perfil de usuario</label>
	<input type="text" name="perfil" id="perfil" class="form-control form-group"required>
	<input type="submit" value="Guardar" class="btn btn-block btn-primary">


{!!form::close()!!}

</div>
@endsection