routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('prueba',function(){
	return view('prueba');
});

Route::get('/', function () {
    return view('welcome');
});
Route::get('menu', function () {
    return view('Plantillas.principal');
});


Route::get('listar', function () {
    return view('clientes.editarCliente');
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix'=>'admin'], function(){
Route::resource('usuario','userController');
Route::resource('cliente','ClienteController');
Route::resource('estadoFactura','Estado_facturaController');
Route::resource('factura','FacturaController');
Route::resource('formaPago','Forma_pagoController');
Route::resource('perfil','PerfilController');
Route::resource('productoFactura','Prod_facturaController');
Route::resource('producto','ProductoController');


});
route::get('eliminar/destroy/{id}','PerfilController@destroy')->name('admin.eliminar');
route::get('eliminarCliente/destroy/{id}','ClienteController@destroy')->name('admin.eliminarCliente');

app/Factura.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Factura extends Model
{
    protected $table='facturas';
    protected $fillable=['Numero_fac','Detalles','idCliente','idFormaPago','idEstadoFactura','CopiaFactura'];
}

app/Http/Controllers/FacturaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Cliente;
use App\Forma_pago;
use App\Estado_factura;
use App\Factura;

class FacturaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cliente=Cliente::all()->pluck('Nombre','id');
        $formaPago=Forma_pago::all()->pluck('FormaPagos','id');
        $estadoFactura=Estado_factura::all()->pluck('Estado','id');;
       return view('factura.crearFactura',compact('cliente','formaPago','estadoFactura'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
     $crearUsuario = new Factura($request->all());
     $crearUsuario->save();
     flash('Factura Guardada');
     return redirect()->route('factura.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/factura/crearFactura.blade.php
@extends('Plantillas.principal')
@extends('Plantillas.librerias')

@section('cuerpo')


<div class="container">

  {{--   <form class="well form-horizontal" action=" " method="post"  id="contact_form"> --}}
      {!! Form::open(['route'=>'factura.store', 'method'=>'post','class'=>'well form-horizontal']) !!}
<fieldset>

<!-- Form Name -->
<legend>Crear factura<br>
  
  @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

  @include('flash::message')

</legend>


<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label">Numero</label>  
  <div class="col-md-6 inputGroupContainer">
  <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-qrcode"></i></span>
  <input  name="Numero_fac" id="numero" placeholder="numero de factura" class="form-control"  type="text">
    </div>
  </div>
</div>

<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label" >Detalles</label> 
    <div class="col-md-6 inputGroupContainer">
    <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-eye-open"></i></span>
  <textarea name="Detalles" id="Detalles" cols="46" rows="6"></textarea>
 
    </div>
  </div>
</div>

<!-- Text input-->
       <div class="form-group">
  <label class="col-md-4 control-label">Cliente</label>  
    <div class="col-md-6 inputGroupContainer">
    <div class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
        {!! form::select('idCliente', $cliente, null, ['class'=>'form-control']) !!}
 
    </div>
  </div>
</div>


<!-- Text input-->
       
<div class="form-group">
    <label class="col-md-4 control-label">Forma de pago</label>  
    <div class="col-md-6 inputGroupContainer">
    <div class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-usd"></i></span>
        {!! form::select('idFormaPago', $formaPago, null, ['class'=>'form-control', 'id'=>'forma']) !!}

    </div>
  </div>
</div>

<!-- Text input-->
      
<div class="form-group">
  <label class="col-md-4 control-label">Estado de factura</label>  
    <div class="col-md-6 inputGroupContainer">
    <div class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-dashboard"></i></span>
  {!!form::select('idEstadoFactura', $estadoFactura, null, ['class'=>'form-control'])!!}
    </div>
  </div>
</div>

<div class="form-group">
  <label class="col-md-4 control-label">Adjuntar</label>  
    <div class="col-md-6 inputGroupContainer">
    <div class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-paperclip"></i></span>
  <input type="file" class="form-control" name="CopiaFactura">
    </div>
  </div>
</div>


<!-- Button -->
<div class="form-group">
  <label class="col-md-4 control-label"></label>
  <div class="col-md-6">
    <button type="submit" class="btn btn-primary" >Guardar <span class="glyphicon glyphicon-send"></span></button>
  </div>
</div>

</fieldset>
{!! Form::close() !!} 
</div>

    </div><!-- /.container -->


  @endsection

resources/views/factura/estadoFactura.blade.php
@extends('Plantillas.principal')
@extends('Plantillas.librerias')

@section('cuerpo')


<div class="container">

 
      {!! Form::open(['route'=>'estadoFactura.store', 'method'=>'post','class'=>'well form-horizontal']) !!}
<fieldset>

<!-- Form Name -->
<legend>Estado de factura<br>
  @include('flash::message')

</legend>


<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label">Estado de factura</label>  
  <div class="col-md-6 inputGroupContainer">
  <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-time"></i></span>
  <input  name="estado" id="estado" placeholder="Ingrese el estado de la factura" class="form-control"  type="text">
    </div>
  </div>
</div>

<div class="form-group">
  <label class="col-md-4 control-label"></label>
  <div class="col-md-6">
    <button type="submit" class="btn btn-warning" >Guardar <span class="glyphicon glyphicon-send"></span></button>
  </div>
</div>

</fieldset>
{!! Form::close() !!} 
</div>

    </div><!-- /.container -->


  @endsection

resources/views/factura/formaPago.blade.php
@extends('Plantillas.principal')
@extends('Plantillas.librerias')

@section('cuerpo')


<div class="container">

 
      {!! Form::open(['route'=>'formaPago.store', 'method'=>'post','class'=>'well form-horizontal']) !!}
<fieldset>

<!-- Form Name -->
<legend>Crear forma de pago<br>
  @include('flash::message')

</legend>


<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label">Forma de pago</label>  
  <div class="col-md-6 inputGroupContainer">
  <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-usd"></i></span>
  <input  name="pago" id="pago" placeholder="Ingrese la forma de pago" class="form-control"  type="text">
    </div>
  </div>
</div>

<div class="form-group">
  <label class="col-md-4 control-label"></label>
  <div class="col-md-6">
    <button type="submit" class="btn btn-primary" >Guardar <span class="glyphicon glyphicon-send"></span></button>
  </div>
</div>

</fieldset>
{!! Form::close() !!} 
</div>

    </div><!-- /.container -->


  @endsection

resources/views/factura/listarEstadoFactura.blade.php
@extends('Plantillas.principal')
@extends('Plantillas.librerias')

@section('cuerpo')
<center><h2>Lista de estados de facturas</h2></center><br>
<a href="{{ route('estadoFactura.create') }}" onclick="return confirm('Desea crear un nuevo estado?')" class="btn btn-info">Crear estado</a><p>
	<table class="table table-striped table-responsive">
		<tr>
			<th>Codigo</th>
			<th>Perfil</th>
			<th style="text-align:right">Editar</th>
			<th style="text-align:right">Borrar</th>
			
		</tr>

		@foreach($estadofactura as $dato)

		<tr>
			
			<td>{{ $dato->id }}</td>
			<td>{{ $dato->Estado}}</td>
			
			<th style="text-align:right"><span><a href=""  class="glyphicon glyphicon-pencil"></span></a></th>
			
			<th style="text-align:right"><span><a href="" onclick="return confirm('Está seguro que desea eliminar el estado '{{$dato->Estado}}' ?')" class="glyphicon glyphicon-trash"></span></a></th>
		</tr>
		@endforeach
	</table>
	<center>{{ $estadofactura->render() }}</center>

	@endsection

resources/views/factura/listarFormaPago.blade.php
@extends('Plantillas.principal')
@extends('Plantillas.librerias')

@section('cuerpo')
<center><h2>Lista de formas de pago</h2></center><br>
<a href="{{ route('formaPago.create') }}" onclick="return confirm('Desea crear un nuevo estado?')" class="btn btn-info">Crear forma de pago</a><p>
	<table class="table table-striped table-responsive">
		<tr>
			<th>Codigo</th>
			<th>Forma de pagos</th>
			<th style="text-align:right">Editar</th>
			<th style="text-align:right">Borrar</th>
			
		</tr>

		@foreach($formapago as $dato)

		<tr>
			
			<td>{{ $dato->id }}</td>
			<td>{{ $dato->FormaPagos}}</td>
			
			<th style="text-align:right"><span><a href=""  class="glyphicon glyphicon-pencil"></span></a></th>
			
			<th style="text-align:right"><span><a href="" onclick="return confirm('Está seguro que desea eliminar la forma de pago'{{$dato->Estado}}' ?')" class="glyphicon glyphicon-trash"></span></a></th>
		</tr>
		@endforeach
	</table>
	<center>{{ $formapago->render() }}</center>

	@endsection